"""logowania

Revision ID: 537594bf47ab
Revises: d2ae485155f9
Create Date: 2023-12-05 23:19:44.095183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537594bf47ab'
down_revision = 'd2ae485155f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liczba_kredytow', sa.Integer(), nullable=True))
        batch_op.drop_column('liczba_logowan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liczba_logowan', sa.INTEGER(), nullable=True))
        batch_op.drop_column('liczba_kredytow')

    # ### end Alembic commands ###
