"""logowania2

Revision ID: fc1d0fe31d50
Revises: 537594bf47ab
Create Date: 2023-12-05 23:21:54.504234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1d0fe31d50'
down_revision = '537594bf47ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liczba_logowan', sa.Integer(), nullable=True))
        batch_op.drop_column('liczba_kredytow')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liczba_kredytow', sa.INTEGER(), nullable=True))
        batch_op.drop_column('liczba_logowan')

    # ### end Alembic commands ###
