DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nazwa TEXT NOT NULL,
    haslo TEXT NOT NULL
);

DROP TABLE IF EXISTS zapytania;

CREATE TABLE zapytania (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nazwa TEXT NOT NULL,
    ip TEXT NOT NULL
);