[tool.poetry]
name = "budzet"
version = "0.1.0"
description = "nic"
authors = ["szalaj <mszalajski@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
